// Generated by scripts/write-docmost-schema.mjs from the schema of a running Docmost
// (scripts/dump-docmost-schema.cjs). Do not edit by hand: dump and regenerate after a Docmost upgrade.
import type { SchemaDump } from "./doc-schema.js";

export const DOCMOST_SCHEMA: SchemaDump = {
  "docmostVersion": "0.96.0",
  "prosemirrorModelVersion": "unknown",
  "topNode": "doc",
  "nodes": [
    [
      "paragraph",
      {
        "content": "inline*",
        "group": "block",
        "attrs": {
          "id": {
            "hasDefault": true,
            "default": null
          },
          "indent": {
            "hasDefault": true,
            "default": 0
          },
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "textAlign": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "codeBlock",
      {
        "content": "text*",
        "marks": "",
        "group": "block",
        "code": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "language": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "mention",
      {
        "group": "inline",
        "inline": true,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "id": {
            "hasDefault": true,
            "default": null
          },
          "label": {
            "hasDefault": true,
            "default": null
          },
          "entityType": {
            "hasDefault": true,
            "default": null
          },
          "entityId": {
            "hasDefault": true,
            "default": null
          },
          "slugId": {
            "hasDefault": true,
            "default": null
          },
          "creatorId": {
            "hasDefault": true,
            "default": null
          },
          "anchorId": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "blockquote",
      {
        "content": "block+",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "bulletList",
      {
        "content": "listItem+",
        "group": "block list",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "hardBreak",
      {
        "group": "inline",
        "inline": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "horizontalRule",
      {
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "listItem",
      {
        "content": "paragraph block*",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "orderedList",
      {
        "content": "listItem+",
        "group": "block list",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "start": {
            "hasDefault": true,
            "default": 1
          },
          "type": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "text",
      {
        "group": "inline"
      }
    ],
    [
      "doc",
      {
        "content": "block+ footnotes?",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "heading",
      {
        "content": "inline*",
        "group": "block",
        "attrs": {
          "id": {
            "hasDefault": true,
            "default": null
          },
          "indent": {
            "hasDefault": true,
            "default": 0
          },
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "textAlign": {
            "hasDefault": true,
            "default": null
          },
          "level": {
            "hasDefault": true,
            "default": 1
          }
        }
      }
    ],
    [
      "taskList",
      {
        "content": "taskItem+",
        "group": "block list",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "taskItem",
      {
        "content": "paragraph block*",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "checked": {
            "hasDefault": true,
            "default": false
          }
        }
      }
    ],
    [
      "mathInline",
      {
        "group": "inline",
        "inline": true,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "text": {
            "hasDefault": true,
            "default": ""
          }
        }
      }
    ],
    [
      "mathBlock",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "text": {
            "hasDefault": true,
            "default": ""
          }
        }
      }
    ],
    [
      "details",
      {
        "content": "detailsSummary detailsContent",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "open": {
            "hasDefault": true,
            "default": false
          }
        }
      }
    ],
    [
      "detailsContent",
      {
        "content": "block*",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "detailsSummary",
      {
        "content": "inline*",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "table",
      {
        "content": "tableRow+",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "tableCell",
      {
        "content": "(paragraph | heading | bulletList | orderedList | taskList | blockquote | callout | image | video | audio | subpages | attachment | mathBlock | details | codeBlock)+",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "colspan": {
            "hasDefault": true,
            "default": 1
          },
          "rowspan": {
            "hasDefault": true,
            "default": 1
          },
          "colwidth": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": null
          },
          "backgroundColor": {
            "hasDefault": true,
            "default": null
          },
          "backgroundColorName": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "tableRow",
      {
        "content": "(tableCell | tableHeader)*",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "tableHeader",
      {
        "content": "(paragraph | heading | bulletList | orderedList | taskList | blockquote | callout | image | video | audio | subpages | attachment | mathBlock | details | codeBlock)+",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "colspan": {
            "hasDefault": true,
            "default": 1
          },
          "rowspan": {
            "hasDefault": true,
            "default": 1
          },
          "colwidth": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": null
          },
          "backgroundColor": {
            "hasDefault": true,
            "default": null
          },
          "backgroundColorName": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "youtube",
      {
        "group": "block",
        "inline": false,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": null
          },
          "start": {
            "hasDefault": true,
            "default": 0
          },
          "width": {
            "hasDefault": true,
            "default": 640
          },
          "height": {
            "hasDefault": true,
            "default": 480
          }
        }
      }
    ],
    [
      "image",
      {
        "group": "block",
        "inline": false,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "width": {
            "hasDefault": true,
            "default": null
          },
          "height": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": "center"
          },
          "alt": {
            "hasDefault": true,
            "default": null
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "aspectRatio": {
            "hasDefault": true,
            "default": null
          },
          "placeholder": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "video",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "alt": {
            "hasDefault": true,
            "default": null
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          },
          "width": {
            "hasDefault": true,
            "default": null
          },
          "height": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": "center"
          },
          "aspectRatio": {
            "hasDefault": true,
            "default": null
          },
          "placeholder": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "audio",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "placeholder": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "pdf",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "name": {
            "hasDefault": true,
            "default": null
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "width": {
            "hasDefault": true,
            "default": 800
          },
          "height": {
            "hasDefault": true,
            "default": 600
          },
          "placeholder": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "pageBreak",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "callout",
      {
        "content": "block+",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "type": {
            "hasDefault": true,
            "default": "info"
          },
          "icon": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "attachment",
      {
        "group": "block",
        "inline": false,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "url": {
            "hasDefault": true,
            "default": ""
          },
          "name": {
            "hasDefault": true,
            "default": null
          },
          "mime": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          },
          "placeholder": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "drawio",
      {
        "group": "block",
        "inline": false,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "title": {
            "hasDefault": true,
            "default": null
          },
          "alt": {
            "hasDefault": true,
            "default": null
          },
          "width": {
            "hasDefault": true,
            "default": null
          },
          "height": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "aspectRatio": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": "center"
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "excalidraw",
      {
        "group": "block",
        "inline": false,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "title": {
            "hasDefault": true,
            "default": null
          },
          "alt": {
            "hasDefault": true,
            "default": null
          },
          "width": {
            "hasDefault": true,
            "default": null
          },
          "height": {
            "hasDefault": true,
            "default": null
          },
          "size": {
            "hasDefault": true,
            "default": null
          },
          "aspectRatio": {
            "hasDefault": true,
            "default": null
          },
          "align": {
            "hasDefault": true,
            "default": "center"
          },
          "attachmentId": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "embed",
      {
        "group": "block",
        "inline": false,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "src": {
            "hasDefault": true,
            "default": ""
          },
          "provider": {
            "hasDefault": true,
            "default": ""
          },
          "align": {
            "hasDefault": true,
            "default": "center"
          },
          "width": {
            "hasDefault": true,
            "default": 800
          },
          "height": {
            "hasDefault": true,
            "default": 600
          }
        }
      }
    ],
    [
      "subpages",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "columns",
      {
        "content": "column+",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "layout": {
            "hasDefault": true,
            "default": "two_equal"
          },
          "widthMode": {
            "hasDefault": true,
            "default": "normal"
          }
        }
      }
    ],
    [
      "column",
      {
        "content": "block+",
        "group": "block",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "width": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "status",
      {
        "group": "inline",
        "inline": true,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "text": {
            "hasDefault": true,
            "default": ""
          },
          "color": {
            "hasDefault": true,
            "default": "gray"
          }
        }
      }
    ],
    [
      "transclusionSource",
      {
        "content": "(paragraph | heading | blockquote | codeBlock | horizontalRule | bulletList | orderedList | taskList | image | video | audio | attachment | callout | details | embed | mathBlock | table | drawio | excalidraw | pdf | subpages | columns | youtube)+",
        "group": "block",
        "attrs": {
          "id": {
            "hasDefault": true,
            "default": null
          },
          "dir": {
            "hasDefault": true,
            "default": "auto"
          }
        }
      }
    ],
    [
      "transclusionReference",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "sourcePageId": {
            "hasDefault": true,
            "default": null
          },
          "transclusionId": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "base",
      {
        "group": "block",
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "pageId": {
            "hasDefault": true,
            "default": null
          },
          "pendingKey": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "footnotes",
      {
        "content": "footnote*",
        "group": "",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "class": {
            "hasDefault": true,
            "default": "footnotes"
          }
        }
      }
    ],
    [
      "footnote",
      {
        "content": "paragraph+",
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "id": {},
          "data-id": {}
        }
      }
    ],
    [
      "footnoteReference",
      {
        "content": "text*",
        "group": "inline",
        "inline": true,
        "atom": true,
        "attrs": {
          "dir": {
            "hasDefault": true,
            "default": "auto"
          },
          "class": {
            "hasDefault": true,
            "default": "footnote-ref"
          },
          "data-id": {
            "hasDefault": true,
            "default": null
          },
          "referenceNumber": {
            "hasDefault": true,
            "default": null
          },
          "href": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ]
  ],
  "marks": [
    [
      "link",
      {
        "inclusive": false,
        "attrs": {
          "href": {
            "hasDefault": true,
            "default": null
          },
          "target": {
            "hasDefault": true,
            "default": "_blank"
          },
          "rel": {
            "hasDefault": true,
            "default": "noopener noreferrer nofollow"
          },
          "class": {
            "hasDefault": true,
            "default": null
          },
          "title": {
            "hasDefault": true,
            "default": null
          },
          "internal": {
            "hasDefault": true,
            "default": false
          }
        }
      }
    ],
    [
      "textStyle",
      {
        "attrs": {
          "color": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ],
    [
      "bold",
      {}
    ],
    [
      "code",
      {
        "excludes": "_",
        "code": true
      }
    ],
    [
      "italic",
      {}
    ],
    [
      "strike",
      {}
    ],
    [
      "underline",
      {}
    ],
    [
      "comment",
      {
        "inclusive": false,
        "attrs": {
          "commentId": {
            "hasDefault": true,
            "default": null
          },
          "resolved": {
            "hasDefault": true,
            "default": false
          }
        }
      }
    ],
    [
      "superscript",
      {}
    ],
    [
      "subscript",
      {}
    ],
    [
      "highlight",
      {
        "attrs": {
          "color": {
            "hasDefault": true,
            "default": null
          },
          "colorName": {
            "hasDefault": true,
            "default": null
          }
        }
      }
    ]
  ]
};
